version: '3.7'

services:
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:latest
    container_name: zabbix-server
    restart: always
    ports:
      - "10051:10051"
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=senha_zabbix
    depends_on:
      - db
    networks:
      - zbx_net

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:latest
    container_name: zabbix-web
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_SERVER_HOST=db
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=senha_zabbix
    depends_on:
      - db
    networks:
      - zbx_net

  db:
    image: postgres:latest
    container_name: zabbix-db
    restart: always
    environment:
      - POSTGRES_USER=zabbix
      - POSTGRES_PASSWORD=senha_zabbix
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - zbx_net

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - zabbix-server
    networks:
      - zbx_net

networks:
  zbx_net:
    driver: bridge
